# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  

steps:
- task: VaultReadKV@2
  inputs:
    strUrl: 'https://hvp.akeyless.io'
    ignoreCertificateChecks: true
    strAuthType: 'clientToken'
    strToken: 'p-vm6u5y7aqnb3am..wrHRk8YYIPnWWx8nGy/uMPUavDx7kvAmhA5/6eJPYLA='
    strKVEnginePath: '/secret/data'
    kvVersion: 'v1'
    strSecretPath: '/Sandbox/2 - Static/Example'
    strPrefixType: 'custom'
    replaceCR: 'false'
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
